POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "Viimeinen testi toivottavasti22",
    "author": "Joku kirjoittaja",
    "url": "https://wwww.testiblogi.com",
    "userId": "643c2a1ba426df3c310dc35a",
    "likes": 54245
}